### ISSUE TITLE
[FEATURE] option to add skills to dropdown in roll dialogue

### ISSUE THREAD

**Issue by DWRoelands** [Rayji96/foundry-V5#115]
If I'm trying to build a dice pool of Strength & Brawl, the natural steps are to click on "Stength" and then select "Brawl" from the drop-down to complete the dice pool.  Instead, when I click on "Strength", I get a dropdown of Attributes rather than skills.  Please see attached screenshot.
![CharSheetBug](https://user-images.githubusercontent.com/829031/140537228-35fe1135-2533-4c36-9545-4e0620b3387d.png)

**Comment by Rayji96** [comment]
This is somewhat intentional. If you want Brawl + Strength, you click Brawl first. It's this way because sometimes you want to roll Wits + Resolve or any other combination of attributes but IIRC never a combination of skills.
It is a little confusing to get started with though as I'd imagine many storytellers ask for rolls with attributes first followed by skill.
Idk what a good solution is but as it is rn is the best I can come up with haha.
Let me know any concerns or suggestions, else close the ticket :)

**Comment by DWRoelands** [comment]
Including the skills in the dropdown might be a feasible solution that
wouldn't disturb the layout of the dialog box; the nine attributes,a line
of dashes for a visual divider, and then the skills?

I'm familiarizing myself with the code, but don't feel comfortable
enough to submit a pull request yet.  Also, thank you very much for all of
the hard work you've obviously put into this.

--Duane

**Comment by Rayji96** [comment]
That makes the drop-down obscenely long :(
I've considered shift-clicking to open the dialogue with skills instead but that seems not self-explanatory either.

**Comment by DWRoelands** [comment]
Could it be implemented as a configuration choice at the module level,
giving the admin the choice about which behavior they prefer?

**Comment by Rayji96** [comment]
Sure. I can add a world scope setting to add skills and abilities to the same drop-down.

**Comment by DWRoelands** [comment]
That would be great!
