### ISSUE TITLE
[BUG] Polish translation needs more expansive font

### ISSUE THREAD

**Issue by Njakuu** [Rayji96/foundry-V5#128]
**Describe the bug**
Default font doesnt have polish(translation) characters (ąęźćżł, etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/95936724/147384604-4d8ca573-9a5a-408c-8f87-ca4bf623b3fc.png)

**Additional context**
This version of font should work (I used free .ttf to .woff converter locally):
https://fonts.google.com/specimen/Cormorant

**Comment by gbursson** [comment]
A workaround:
Use Custom CSS module, and replace the font(s) you want. I had to do it for my World, as I could not stand Polish diacritics messed up.

**Comment by Veilza** [comment]
This was fixed with commits 150c1f5798a41d972107047b8c86e2a750c6f748 and 5100ca3c6c21b0e4b5858cba783c17b21d49db68 with the swap from Cormorant to Vollkorn. (Screenshot below to reference with the original issue's)
![image](https://github.com/Rayji96/foundry-V5/assets/113429647/ac3bc676-b03d-4b42-a5da-a3d16a14725a)
