### ISSUE TITLE
[FEATURE] Contested Power Rolls

### ISSUE THREAD

**Issue by DachDolan** [Rayji96/foundry-V5#211]
**Is your feature request related to a problem? Please describe.**
The ability to trigger a contested roll with certain powers.

**Describe the solution you'd like**
A check box in the power item category that you can toggle if the power calls for a contested roll, and then two drop down boxes to mark what polls to be used by the targeted token. Then, like with pathfinder module, the targeted token/player can click a hyperlink in the power roll that will trigger their contested roll and compare the two rolls results.

**Comment by Veilza** [comment]
I really like this idea! I can add it to my personal to-do list along with other upgrades and quality of life features to the way dice are rolled.

It'll be a while before I can get around to this though because first I have to dig into the backend of the dice and fix that up to a better degree, but afterwards I'll be happy to implement contested rolls as a feature to the system.
