### ISSUE TITLE
[UI] [not really a BUG] Name/Clan/Predator Fields not visually separated

### ISSUE THREAD

**Issue by gbursson** [Rayji96/foundry-V5#229]
**Describe the bug**
Not really a bug, Name, Clan and Preadtor Type fields blend together, and are left-aligned.
Ideally, those should be centred/spread across the sheet and visually separated.

![image](https://github.com/Rayji96/foundry-V5/assets/1756600/8e237708-9d51-4cdb-bd6e-05bc727b6809)

**Comment by Veilza** [comment]
I would be willing to centre-align these fields, but otherwise, them "blending together" is a stylistic choice--there's almost never reason to ever edit these fields and unless you have an extremely long name, clan name, or predator type, these fields will never overlap or otherwise need a reason for the separation and thus look best when they do almost seem apart of the sheet itself.

Unless there's a big push to change it, I won't likely be changing this beyond as I said, centre-aligning the text. It would look--in my opinion--uglier and less clean with borders or other separation.
