### ISSUE TITLE
[FEATURE] Werewolf V5 Improvements

### ISSUE THREAD

**Issue by Adridraco15** [Rayji96/foundry-V5#257]
Hi, I'm a Werewolf the apocalypse Master, and I came here first to thank you for the work you are doing porting the Werewolf Five edition system to Foundry. That's not the only reason, I've come to give some comments to the port system.
Disclaimer: Some images used are from the 20th anniversary system at foundry.

-On **Shapechange**, that physical bonuses should automatically apply to the specified rolls.
![image](https://github.com/Rayji96/foundry-V5/assets/102964204/84398399-ec59-48c1-bc81-810e385fe8e1)

-A section where **Fetishes/Talismans** can be placed with their die roll systems similar to Gifts. _[I'm currently doing that]_ Since they are not expandable in the backgrounds section. _[For the convenience of the players]_

-To be able to put an option to automatically remove Willpower when using a Gift _[And the amount it takes away]_. Like when you do a Reroll.

-And the last thing to suggest to add to the sheet is a personal space, where to describe the character. _[Not Urgent]_
Like this:
![image](https://github.com/Rayji96/foundry-V5/assets/102964204/1d99ab9e-9e51-43cd-850e-e2cbec5a3c42)

-Compatibility with Chat Roller by the Werewolf system. 
Rage checks
And replace the Disciplines for Renown [Wisdom, Glory and Honor]
And swap the Dice Png couse in the chat shows the Vampire dices and not the Werewolf dices.
Remove the Rouse and Remorse Button. And put something very usefull like "Step Sideways" or something else...

-This could be more triky but will be glorious if we can roll the dices and have 3d Dices like other VTT Games. That will be awesome.

-A traker in the sheet telling you in wich form is the Player or NPC
Like this:
![image](https://github.com/Rayji96/foundry-V5/assets/102964204/be4957ff-b489-45c9-bd93-8212faa19247)

Having said that, thank you very much for what you do and I hope I can be of help.

**Comment by Veilza** [comment]
Thank you so much for all the feedback and suggestions!

- Talismans are on the to-do list, but I haven't made an official issue for them.
- Dice roller is going to take a lot of time to rework and fix; see #215 
- 3D dice are handled by our integration with the Dice So Nice module; I strongly suggest using Dice So Nice if you want 3D dice, because there is no way the system is going to implement them as part of the core system (it's just too much.)
- Automatically spending Willpower when using a gift seems like it'd be useful, could you point me to any Werewolf powers (by name) in V5 that do so? I thought I checked and didn't see any is the only reason why I never gave the option before.
- Different forms adding bonuses is part of #234 , so actively being worked on.

**Comment by imynwulf** [comment]
Here's some of the gifts that require willpower as all or part of their activation costs. 

Catfeet, Eyes of the Owl, Penumbral Senses, Sharpened Senses, Thwarting the Arrow, Tongue of the Beasts, Blissful Ignorance, Spider's Song, Pulse of the Prey, Scent of running water, Luna's blessing (requires both a rage check and a willpower), Thieving talons of the magpie

It looks like it's roughly 50/50 as to the gifts requiring a rage check or willpower expenditure to activate them. I only considered the unique gifts though.

**Comment by Veilza** [comment]
Ah, you're right! There are several powers that require willpower expenditure I overlooked.

I'll make sure that gets into the system with the next big release.

**Comment by eivil** [comment]
I would add to this some other suggestions and very minor/nitpicky adjustments to make the sheet more in line with the game:

- In the **Header**: perhaps adding a small checkbox like the one for Despair in the Hunter sheet, to mark characters which have broken their Tribe Bans, as a reminder for storytellers to limit their WP recovery at the start of the next session
- In the **Header**: move the Rage/Rouse check button to inside the Rage/Hunger as opposed to it separate box (maybe replacing it with a visual tracker of the character's current Form in the werewolf sheet and the characters current Resonance/Temperament in vampire)
 
- In **Gifts & Rites**: Some way of marking each Renown category with Chagrin (maybe another checkbox?). Chagrin temporarily reduces the equivalent Renown score by 1 (or 2) until resolved, but a visual marker alone would already be great
 
- In **Features**: Maybe remove the Boons category of Feature in the werewolf sheet, since it isn't used in W5
 
- In **Description**: Maybe remove the Ambition and Desire boxes, as well as removomg convictions from Touchstones & Convictions, since these came from VtM and are not used in Werewolf.

**Comment by Adridraco15** [comment]
Hello!! Here again, after several sesions in my table, I have noticed several things that would be very good, and if it is true that one of them, is very necessary to Masters.

I use as a reference this image of the actual version.
![image](https://github.com/Rayji96/foundry-V5/assets/102964204/181d8210-ac42-47f7-8b0b-3168d1190a49)


- Creation of sheet antagonists for the Werewolf World; 
In this version if the master wants to do an Enemy in Werewolf following the rules, you need a replace of Standard Dice Pools for a POWER Pool [This is not a heavy problem, I put the same amount of Dice in Every Standard Pool, but could be better :D ]
[Or differentiating each sheets like 20 Aniversary]
![image](https://github.com/Rayji96/foundry-V5/assets/102964204/90a33be2-9519-4902-bf39-d2153e91124b)


Second, and this is relly relevant, in the slot of Disciplines, change it to Charms And Gifts. Like in a Character sheet, where you can write a description of them and change the system, just only maintaining the actual sistem of pool, just putting a pool whit a number, that's good. 👍
[actually I put the descriptions in the Notes, and tips for me saying "Hey master, this Gift throw that pool whith Animalism Instead" and is very messy if you have too many characters.]
![image](https://github.com/Rayji96/foundry-V5/assets/102964204/d036215e-541d-4b8a-86d5-fcbaceedbe42)


- Third, an option to add dices whit NPC sheets, like a character sheet. In some cases when a Player do a Confronted Check or your NPC gain X cuantity of dices that turn/attack/action. [Just whit a Modifier and Difficulty]
![image](https://github.com/Rayji96/foundry-V5/assets/102964204/7cba1088-7bb2-4a0d-90da-2e14c87d1a49)


- Important one for Vamire and Werewolf, have a Rage/Hunger cheker and the respectives Dices of teh systems whit the NPCs. This to facilitate the interaction whit the master and fluid experience. Because, having to make Sheets for each NPC is very tedious, in the same way that a player has to do it.

A solution for this is, like the last Point put a Hunger/Rage Dice [maybe to not break your heads mainig code :D you can put a modifier of "Special dices" changing the amonunt of dices for that Hunger/Rage/Desperation Dices, all we know whats mean in each system, but if you can put the differentiation between the systems in the NPC Sheet, will be perfect!]


- For Another needed interaction. RITES; When you make a Ritual you must add Dice for every participant and every what know the rite. As say in the mecanics of Rites in the page 180. Here's the cap whit the important part.
![image](https://github.com/Rayji96/foundry-V5/assets/102964204/8a1a3951-3b38-4857-b5ad-876cae8f4dc1)

The solution what I see here is Putting;
**Modifire of Participants** [adding one Rage Dice for each one]
**Difficulty**
**Trained Participants** [adding one dice of Rage and other Normal for each one]
**And a Check box of Specialty**, cause you cant use as Rolling especialties in the stats a Rite. [Adding a Dice to the Main Pool of the Ritual Master].

Thank you for your support and contious supportting, if you need something we are here to help :D See you soon!

**Comment by eivil** [comment]
I'm pretty sure most of these suggestions are either already planned or in the works, [Adridraco15](https://github.com/Adridraco15). I suggest checking out the other posts and the most recent feature board ( https://github.com/Rayji96/foundry-V5/projects/2 )
