### ISSUE TITLE
[FEATURE] Colorblind accessibility.

### ISSUE THREAD

**Issue by robomagon** [Rayji96/foundry-V5#290]
So I have photophobia and need to use dark mode, but I'm also colorblind and can't distinguish the red filled dots from the black empty ones. Same issue with health/willpower boxes.

It would be really helpful to have the option to change the color of the dots and slash marks. Or if customizability isn't an option, perhaps just a static choice between red and white.

**Comment by Veilza** [comment]
Colorblind accessibility is definitely something I want to work on soon! It'll probably come with the overall redesign of the sheets to be more accessible, which will include making some buttons more obvious and doing my best to make things easier to navigate and read.

Thank you for creating an issue about this, I'll try to work on it when I can!

**Comment by Veilza** [comment]
Until I can add an actual option to customize dot colours, I did want your opinion if I was to push out a small update to help with this issue. Would the following be a decent change to help you see the dots and slash marks better? (Old on the left, updated on the right)

![image](https://github.com/Rayji96/foundry-V5/assets/113429647/cec828ca-9f0a-4933-a982-ddd533c7fb4e)

I'm not sure if having the boxes filled in helps much, but please let me know if it does! And feel free to point out any other parts of the sheet that may be hard to read in dark mode.

In the future I do want the customizability to let people change the colours of the sheets as they wish, but because that may be a ways away, I hope I can find a good short-term solution to help out people for now.

**Comment by robomagon** [comment]
The slashes are completely distinguishable on that. Although the empty boxes should probably also be white for consistency. The dots are very slightly better as well. That's just me though. Different colorblind people will have different reds that they can and can't see.

I'll have a look through all the sheets in a bit to see if there are any other places that could be improved.

Also, many thanks for addressing this.

**Comment by Veilza** [comment]
Good idea! I'll adjust the styling a bit more but try to keep the colour contrast to help, at least until I can give the ability to properly edit the sheet colours and all.
