### ISSUE TITLE
[FEATURE] Bunch of Things

### ISSUE THREAD

**Issue by HalflingDeSaoVicente** [Rayji96/foundry-V5#297]
1. Feedbacks.
- The old Specialties system is more intuitive, simple, organized and aesthetic, the new one is useful though. 
- Willpower upgrade is really nice, but kinda confusing if someone is new, maybe instead of adding the rerolled dices into the previous pool, put the new results into the old dices that we choose and grey out them to show which one we rerolled.

2. Feature Requests. 
- Adding Feature for Adding Custom Disciplines (Useful to homebrewing older Disciplines like Dementation, Necromancy, Obtenebration etc..).
- Adding Feature for Compendium for us just to drag the features to character sheet (Like Clan, Generation, Predator Types, Advantages, Discipline Powers etc...).
- Some kind of Relationship Map, to be fair I don't know how it would be created that feature to foundry and how it's gonna be used, just an idea and not a priority.
- Adding Equipament presets with their specific modifiers and an Inventory page.
- When failing into Frenzy Test you'll get automatically the buffs and debuffs expected for being in that state.

**Comment by Veilza** [comment]
Thank you for the feedback! I'll take these into consideration for the future. As for the feature requests...

- Custom disciplines are already planned (#220)
- Dragging features onto the character sheet already planned (#150)
- A relationship map would be.. complicated and would take a lot of work. It's basically a whole different module with no real interfacing with the system itself. It's also not guaranteed to be a useful feature for all storytellers. So it's extremely unlikely.
- Equipment is planned (#255)
- Conditions are planned (#271 

Since the only new suggestion here is the relationship map and it's unlikely to be done, I'm closing this issue but if you have any new suggestions then feel free to open a new issue with them! And in the future please check if a feature request has already been submitted.

**Comment by gbursson** [comment]
I would be against implementing Relationship Map. Not because it is not needed, but it would take a lot of resources, for a limited gain.

For people wanting to have Relationship Maps, with several nice features, I recommend mind map making software (Miro, Lucid), or even Kanka.
