### ISSUE TITLE
[FEATURE] Hunger adding dice, not replacing

### ISSUE THREAD

**Issue by SalithTaydan** [Rayji96/foundry-V5#301]
Would it be possible to get a 'homebrew' option added in which would allow the Hunger dice to be added onto dice pools instead of replacing dice?
Would love to try it out and see how it runs, but I only have an on-line group and we use Foundry (and I have no idea how to write a module or alter the game system in any way).
Thanks.

**Comment by Veilza** [comment]
Generally I try to avoid adding homebrew options to the system when possible, for the sake of other features that the core system needs more development in. If this changes in the future, such as when the system is more fleshed out and stable, then I'll definitely add in something like this and other common homebrew options, but homebrew options aren't something that I can in good faith say I'll put development time towards anytime soon.

If someone else wants to implement such a feature into the system and put in a pull request, then it could be merged in as a setting. But at least for now, it's not planned.

In the interim, if you did want to run something like this, it's easy enough to make a Macro that rolls up to 3 extra dice and subtracts a willpower, it just won't be able to automatically add the total to the previous roll.

If you did want a macro like that, I can type it up real quick for you! Just let me know if this is something that would help you out until the system otherwise supports alternate ways to roll willpower (Though, again, no promises that's *any* time soon.)
