### ISSUE TITLE
[BUG] RUSSIAN localization didn't work properly

### ISSUE THREAD

**Issue by Z6200** [Rayji96/foundry-V5#321]
**Describe the bug**
ru localization translates half of the text
**To Reproduce**
1. Create a world.
2. Start a world

**Expected behavior**
I expect russian localization
**Screenshots**
![image](https://github.com/Rayji96/foundry-V5/assets/170015676/74c09489-6a93-4fd6-8041-7f7536a5eb87)
![image](https://github.com/Rayji96/foundry-V5/assets/170015676/9e3e3952-89ab-4b52-b266-da0d01602ed1)
![image](https://github.com/Rayji96/foundry-V5/assets/170015676/56c8cac5-95c2-44f3-80b1-f256565ba087)

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari] Vivaldi
- FoundryVTT Version [e.g. 22] 11.315
- Foundry-V5 Version [e.g. 22] 4.2.1

**Additional context**

**Comment by Veilza** [comment]
Hello! It seems you're using the Russian localization module, which offers a separate localization from our now-built-in Russian localization. I've confirmed there's issues with it and the World of Darkness localization.

If you are using that module for Russian localization, my recommendation would be the following:
* Go into your "FoundryData" folder.
* "Data"
* "modules"
* "ru-ru"
* "i18n"
* "systems"
* Delete the vtm5e.json file
* Restart your game

Hope this helps! I honestly don't think I can fix this in the system itself, but as we now officially support Russian localization in the system, I would go to the module developer and ask them to please remove vtm5e translations on their end or to fix it so that it doesn't interfere with the system.

**Comment by Veilza** [comment]
Hello! Just an update, I finally narrowed down the issue of what was conflicting between the Russian localization module and the WOD5E system. The latest update should be compatible with the Russian localization module: https://github.com/Rayji96/foundry-V5/releases/tag/4.4.0
