### ISSUE TITLE
[BUG] Health, Willpower, Roll Frenzy issues

### ISSUE THREAD

**Issue by scomick** [Rayji96/foundry-V5#46]
**Describe the bug**
the latest update seems to have broken the health, and willpower tracks. Not only are the health and willpower tracks filling up backwards (the red "full" boxes should be from right to left, with the blanks/damage starting on the left) but rolling for frenzy also seems broken. It should only roll your remaining willpower (blank undamaged willpower in other words, as per p119 of the VTM rulebook under "tracker and tools") + 1/3 of your humanity... but right now it seems to roll the filled out "red" boxes in your willpower instead (although I think it's rolling the 1/3 humanity ok).  

**Expected behavior**
Health and Willpower tracks should have white boxes equal to your health and willpower values. The remainder should be blacked/redded out. These white boxes should be filled with slashes and Xs starting from the left.

Rolling for Resist Frenzy should only roll dice equal to any blank boxes in your willpower (meaning, no slashes or Xs or black/red) and 1/3 of your humanity.

- FoundryVTT Version 0.7.9
- Foundry-V5 Version 1.3

**Comment by Rayji96** [comment]
Ah I think that's a misunderstanding that a lot of us share in the community. I've been playing with filled in squares as full health/willpower. I'll add an option to toggle between the two or something

**Comment by scomick** [comment]
Ah, I getcha. But yeah, I'll admit that's the first time I hear of anyone playing like that haha. Interesting method.  But yeah a toggle would be amazing !

**Comment by bmgraves** [comment]
Just wanted to weight in on this since I was considering trying to work out how to make this happen myself. If you haven't looked at it, the health system from i believe Soulcake(on discord) for their mage20 system(https://gitlab.com/MarlQ/mta0 is really well done.

I'm more of a Python/backend developer than a javascript/web developer, so it's taking me time to work through things, but if you don't have the interest/time in adapting that type of thing, I may try to do that and send a pull request your way. Though As i'm sure we all are, work may get in the way of that. Haha.

**Comment by Rayji96** [comment]
A better solution would be to increment and decrement max hp with a + - next to field header (to account for Fortitude) and only use / and X states, removing filled state.

**Comment by bmgraves** [comment]
@Rayji96 Just wanted to follow up with this. I'm making progress on a solution for health/willpower as per our discord convo(GravyBoat).

Current status in my branch is I have functional +/- Max health/Willpower. I've removed the random "null" state. boxes are added/removed properly with the +/-, and can cycle the clear/superficial/aggrevated damage states (also added right click capability to cycle backwards). 
I have not yet touched humanity since that is kind of a different beast alltogether, but health/willpower work fine and I'll likely be submitting a pull request soon for the feature. 

There are currently some CSS issues to overcome. Any boxes over 10 throw off the the spacing below and begin scrollinng xp/hunger/rouse/frenzy away. They are still viewable/usable up to 20 (which is more than enough really) but I still want to try to clean up the spacing a bit if I can.
