### ISSUE TITLE
[BUG] Dice So Nice show dot on fail instead of blank

### ISSUE THREAD

**Issue by Rayji96** [Rayji96/foundry-V5#54]
**Describe the bug**
IRL VTM dice show blanks instead of dots for failure on dice. We should follow that.

**Acceptance Criteria**
Dice So Nice VTM dice show blanks on a fail instead of dots. Bestial fail stays the same.

**Comment by eisenfuchs** [comment]
I changed the 4 dice asset images with dots to be blank to fix this. it is way easier to read. especially on the chat dice output, in my experience. 

for the result it's not relevant that the fails were on a hunger die or not, that's why making the graphics distinguishable creates more complexity than necessary.

Zev

**Comment by scomick** [comment]
Out of curiosity, is there a reason the dice so nice rolls white dice for regular and not black? And black for hunger, and not red? Dunno if there's a way to change the color setting on my end? My players would like the rolled dice to match the physical ones they're used to, since their brains keep checking the "black" hunger dice as the normal dice out of force of habit

**Comment by eisenfuchs** [comment]
> Out of curiosity, is there a reason the dice so nice rolls white dice for regular and not black? And black for hunger, and not red? Dunno if there's a way to change the color setting on my end? I'm not overly familiar with this module, but from what I can tell in its settings I can only change the colors of the basic dice? My players would like the rolled dice to match the physical ones they're used to, since their brains keep checking the "black" hunger dice as the normal dice out of force of habit, so if anyone has a tip on changing the vtm dice here that'd be great

As far as I understand that all comes from the way dice are shown in chat. Black Symbols require a white background, that's why the dice also are white. Ideally we would use white symbols on black backgrounds in chat AND dice, white symbols on red background in chat AND dice too. I had the exact same thought, but wasn't sure how to fix this on my end. I'm gonna look at it, and see if I can get it to work (I'm not a real web dev tbh, just a UX person), but maybe I can make it work and give some hints on how to do this.

**Comment by eisenfuchs** [comment]
<img width="1440" alt="Bildschirmfoto 2021-03-05 um 20 13 38" src="https://user-images.githubusercontent.com/79832708/110162669-56b09180-7def-11eb-9d3a-8f5933344add.png">

Making the dice black wasn't hard. But I'm struggling with the RED dice. They are pink in my case, and I don't know where to set up the colorset for the hunger dice.

**Comment by scomick** [comment]
What's the process you used to make this happen? I can live with pink dice since it's pretty close to red

**Comment by eisenfuchs** [comment]
> What's the process you used to make this happen? I can live with pink dice since it's pretty close to red

if you want to just do it yourself, you need to change the DSN icons in the assets folder to white, and go to main.js and set the colorset of the default dice to black, and the hunger dice to "red" (but it will be pink). but I'm currently trying to setup my developer environment so I can help contribute to this project.

you got me inspired!

**Comment by scomick** [comment]
Sorry, are we talking about the main.js in the systems\vtm5e\module folder? (Sorry I'm not a coder at all lol)  what am I looking for exactly in that file with regards to changing the dice color? 

I've already changed my icons to white at least lol

**Comment by scomick** [comment]
![image](https://user-images.githubusercontent.com/79115220/110167338-9e212880-7dc3-11eb-8a37-f1378a6db331.png)

Looks like just adjusting the dice color in the settings in foundry after works to make the hunger die red

**Comment by eisenfuchs** [comment]
I fixed it, it's on my fork. I'm making a pull request, and we all get the new dice!

![Uploading Bildschirmfoto_2021-03-05_um_21.21.44.png…]()
