### ISSUE TITLE
[FEATURE] Integration with Simple Dice Roller module

### ISSUE THREAD

**Issue by scomick** [Rayji96/foundry-V5#59]
Simple Dice Roller is a great tool for quick dice rolls and players who aren't great at manually typing commands. Would be neat to have a way to roll "dvs" and "dhs"

![image](https://user-images.githubusercontent.com/79115220/110168284-f4429b80-7dc4-11eb-8f74-a71336dc15ec.png)

**Comment by Rayji96** [comment]
Have other systems integrated with Simple Dice Roller?
I took a quick peak at the repo: https://github.com/jopeek/fvtt-simple-dice-roller and didn't see any instructions on integrating :(
Wondering if it's even possible

**Comment by paercebal** [comment]
I actually tried something (despite my Javascript-Fu being 15 years old).

![image](https://user-images.githubusercontent.com/15169954/113535666-595ffb80-95d4-11eb-9d94-ab1cd7677779.png)
![image](https://user-images.githubusercontent.com/15169954/113535700-7ac0e780-95d4-11eb-9c93-43b09f70d5a0.png)

While I don't believe integration is possible either in the current state, I might be possible to simply copy/paste the code into your Foundry V5 system, adding an icon to the leftmost toolbar, like Simple Dice Roller did. That would "unblock" people wanting this.

Another solution would be to provide a module heavily inspired by the Simple Dice Roller, adding the V5 button, and providing the dice rolls. But that would be a lot of copy-paste everywhere.

Last but not least, it would need a refactoring of Simple Dice Roller, and to be fair, my knowledge of VTT/Javascript reaches its limits, and I would need regular reviews/answers to make sure I'm not fumbling something.

I'll need to talk to the author of Simple Dice Roller for his input/feedback/authorization.

What would be your preference?

Mine would be the full copy-paste, if only because I would be able to use it on my VTT, just by pointing to my Github, without needing to interfere with any other module.

**Comment by paercebal** [comment]
I did a small hack here: https://github.com/paercebal/fvtt-simple-dice-roller-v5
I will contact the original author for feedback.

**Comment by DWRoelands** [comment]
The visual of the Vampire dice alone is pretty exciting.  Have you been able to make any headway?

**Comment by Rayji96** [comment]
The visual dice comes from already built in Dice So Nice integration :)
Still no docs on how to integrate with Simple Dice Roller on their repo :(

**Comment by Rayji96** [comment]
@paercebal I'd recommend you publish that as a module with permission from the original author. I don't believe there's intended integration with custom dice with the original mod so I'll be closing this issue until something changes.
